# Generated by Django 5.1.6 on 2025-04-01 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='Fichier PDF')),
                ('prix', models.JSONField(blank=True, null=True, verbose_name='Prix')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='books.book', verbose_name='Livre')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Utilisateur ayant créé l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, help_text='Utilisateur ayant mis à jour l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'PDF de livre',
                'verbose_name_plural': 'PDFs de livres',
            },
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('link', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Lien')),
                ('download_limit', models.PositiveIntegerField(default=5, verbose_name='Limite de téléchargements')),
                ('downloads_used', models.PositiveIntegerField(default=0, verbose_name='Téléchargements utilisés')),
                ('book_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='pdf.bookpdf', verbose_name='PDF')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Utilisateur ayant créé l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, help_text='Utilisateur ayant mis à jour l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Lien de téléchargement',
                'verbose_name_plural': 'Liens de téléchargement',
            },
        ),
    ]
