# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacopeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('monograph_code', models.CharField(help_text='Code de la monographie (ex. Ph. Eur.)', max_length=50, unique=True)),
                ('purity_criteria', models.JSONField(default=dict, help_text="Critères de pureté (ex. {'pH': '6.0-7.0'})")),
                ('quality_tests', models.JSONField(default=dict, help_text="Tests de qualité (ex. {'identification': 'IR'})")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produit Pharmacopée',
                'verbose_name_plural': 'Produits Pharmacopée',
            },
        ),
    ]
