# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacope', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacopeproduct',
            name='base_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='product.baseproduct'),
        ),
    ]
