# Generated by Django 5.1.6 on 2025-03-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('marcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='categories',
            field=models.ManyToManyField(help_text='Catégories de pharmacopée associées au docteur.', limit_choices_to={'category_type': 'pharmacy'}, related_name='doctors', to='category.category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='mark',
            name='categories',
            field=models.ManyToManyField(help_text='Catégories non technologiques associées à la marque.', limit_choices_to={'is_non_tech': True}, related_name='marks', to='category.category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='mark',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(help_text='Catégories commerciales associées à la boutique.', limit_choices_to={'category_type__in': ['commercial']}, related_name='shops', to='category.category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Sous-catégories associées à la boutique (optionnel).', related_name='shops', to='category.subcategory', verbose_name='Sous-catégories'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='categories',
            field=models.ManyToManyField(help_text='Catégories associées au supermarché.', related_name='supermarkets', to='category.category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
