# Generated by Django 5.1.6 on 2025-03-14 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Score de tendance')),
                ('period', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20, verbose_name='Période')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calculé le')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='product.baseproduct', verbose_name='Produit de base')),
            ],
            options={
                'verbose_name': 'Tendance',
                'verbose_name_plural': 'Tendances',
                'ordering': ['-score', '-calculated_at'],
                'unique_together': {('base_product', 'period', 'calculated_at')},
            },
        ),
    ]
