# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text='Nom de la catégorie (ex. Livres, Réservations).', max_length=255, verbose_name='Nom')),
                ('category_type', models.CharField(choices=[('book', 'Livre'), ('reservation', 'Réservation'), ('service', 'Service'), ('pharmacy', 'Pharmacopée'), ('commercial', 'Commercial')], help_text='Type ou domaine (ex. Livre, Service).', max_length=50, verbose_name='Type de catégorie')),
                ('is_non_tech', models.BooleanField(default=False, help_text='Indique si la catégorie est non technologique (ex. livres physiques).', verbose_name='Non technologique')),
                ('image', models.ImageField(blank=True, help_text='Image optionnelle pour affichage.', null=True, upload_to='categories/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text="Classe FontAwesome (ex. 'fa-book') pour affichage.", max_length=100, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text='Nom de la sous-catégorie (ex. Romans).', max_length=255, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, help_text='Image optionnelle pour affichage.', null=True, upload_to='subcategories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['name'],
            },
        ),
    ]
