# Generated by Django 5.1.6 on 2025-03-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Catégorie à laquelle cette sous-catégorie est rattachée.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category', verbose_name='Catégorie parent'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
