# Generated by Django 5.1.6 on 2025-03-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payement', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devise',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='payement.devise'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='payement.devise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commande',
            field=models.ForeignKey(help_text='Commande associée à cette facture.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='product.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='commande',
            field=models.ForeignKey(help_text='Commande associée à ce paiement.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='product.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payement.devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payement.paymentmethod', verbose_name='Méthode'),
        ),
    ]
