# Generated by Django 5.1.6 on 2025-04-01 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='ville',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='adresse',
            old_name='code_postal',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='adresse',
            old_name='rue',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='tauxechange',
            name='taux',
            field=models.FloatField(help_text='Taux de conversion (ex. 1 EUR = 1.2 USD)', validators=[django.core.validators.MinValueValidator(0.01, 'Le taux doit être positif.')], verbose_name='Taux'),
        ),
    ]
