# Generated by Django 5.1.6 on 2025-04-05 12:12

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_adresse_created_by_alter_adresse_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxechange',
            name='taux',
            field=models.DecimalField(decimal_places=6, help_text='Taux de conversion (ex. 1 EUR = 1.2 USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Taux'),
        ),
        migrations.AddIndex(
            model_name='adresse',
            index=models.Index(fields=['postal_code', 'city'], name='utils_adres_postal__c4a354_idx'),
        ),
    ]
