# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique (UUID v4) non modifiable.', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date et heure de création (non modifiable).', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.', verbose_name='Date de mise à jour')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 à 5', verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire laissé par l’utilisateur', verbose_name='Commentaire')),
                ('type', models.CharField(choices=[('reservation', 'Réservation'), ('product', 'Produit'), ('service', 'Service'), ('pharmacy', 'Pharmacopée'), ('commercial', 'Commercial')], help_text='Type d’entité concernée (ex. produit, réservation)', max_length=20, verbose_name='Type')),
                ('product_id', models.CharField(help_text='Identifiant de l’entité (ex. UUID produit, ID réservation)', max_length=255, verbose_name='ID de l’entité')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
