# Generated by Django 5.1.6 on 2025-03-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('marcher', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Sous-catégorie du produit (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_products', to='category.subcategory', verbose_name='Sous-catégorie'),
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='book_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='company',
            field=models.ForeignKey(help_text='Compagnie publiant ou vendant le livre.', on_delete=django.db.models.deletion.CASCADE, related_name='book_products', to='marcher.company', verbose_name='Compagnie'),
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cart',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur auquel appartient le panier.', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book_product',
            field=models.ForeignKey(blank=True, help_text='Produit livre dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.bookproduct', verbose_name='Produit livre'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='Panier auquel cet élément appartient.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.cart', verbose_name='Panier'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='commande',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='Panier associé à cette commande (optionnel après finalisation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='product.cart', verbose_name='Panier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur qui a passé la commande.', on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='company',
            field=models.ForeignKey(help_text='Compagnie vendant le produit.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marcher.company', verbose_name='Compagnie'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='company_product',
            field=models.ForeignKey(blank=True, help_text='Produit d’entreprise dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.companyproduct', verbose_name="Produit d'entreprise"),
        ),
        migrations.AddField(
            model_name='markproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='mark_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='markproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='markproduct',
            name='mark',
            field=models.ForeignKey(help_text='Marque à laquelle le produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marcher.mark', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mark_product',
            field=models.ForeignKey(blank=True, help_text='Produit de marque dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.markproduct', verbose_name='Produit de marque'),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='doctor',
            field=models.ForeignKey(help_text='Docteur proposant le produit.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marcher.doctor', verbose_name='Docteur'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pharmacy_product',
            field=models.ForeignKey(blank=True, help_text='Produit pharmacopée dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.pharmacyproduct', verbose_name='Produit pharmacopée'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='company_product',
            field=models.ForeignKey(blank=True, help_text='Produit d’entreprise concerné par la promotion (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product.companyproduct', verbose_name="Produit d'entreprise"),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='review',
            name='book_product',
            field=models.ForeignKey(blank=True, help_text='Produit livre auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.bookproduct', verbose_name='Produit livre'),
        ),
        migrations.AddField(
            model_name='review',
            name='company_product',
            field=models.ForeignKey(blank=True, help_text='Produit d’entreprise auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.companyproduct', verbose_name="Produit d'entreprise"),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='review',
            name='mark_product',
            field=models.ForeignKey(blank=True, help_text='Produit de marque auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.markproduct', verbose_name='Produit de marque'),
        ),
        migrations.AddField(
            model_name='review',
            name='pharmacy_product',
            field=models.ForeignKey(blank=True, help_text='Produit pharmacopée auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.pharmacyproduct', verbose_name='Produit pharmacopée'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(help_text='Boutique à laquelle le produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marcher.shop', verbose_name='Boutique'),
        ),
        migrations.AddField(
            model_name='review',
            name='shop_product',
            field=models.ForeignKey(blank=True, help_text='Produit de boutique auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.shopproduct', verbose_name='Produit de boutique'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop_product',
            field=models.ForeignKey(blank=True, help_text='Produit de boutique concerné par la promotion (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product.shopproduct', verbose_name='Produit de boutique'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shop_product',
            field=models.ForeignKey(blank=True, help_text='Produit de boutique dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.shopproduct', verbose_name='Produit de boutique'),
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produit de base auquel ce produit est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_products', to='product.baseproduct', verbose_name='Produit de base'),
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text="Utilisateur ayant créé l'entrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='supermarket',
            field=models.ForeignKey(help_text='Supermarché vendant le produit.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marcher.supermarket', verbose_name='Supermarché'),
        ),
        migrations.AddField(
            model_name='review',
            name='supermarket_product',
            field=models.ForeignKey(blank=True, help_text='Produit de supermarché auquel l’avis est rattaché (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.supermarketproduct', verbose_name='Produit de supermarché'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='supermarket_product',
            field=models.ForeignKey(blank=True, help_text='Produit de supermarché concerné par la promotion (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product.supermarketproduct', verbose_name='Produit de supermarché'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='supermarket_product',
            field=models.ForeignKey(blank=True, help_text='Produit de supermarché dans le panier (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.supermarketproduct', verbose_name='Produit de supermarché'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='unique_active_cart_per_user'),
        ),
    ]
