# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('product', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Utilisateur ayant créé l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='utils.devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.subcategory', verbose_name='Sous-catégorie'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Utilisateur ayant mis à jour l’entrée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AddIndex(
            model_name='baseproduct',
            index=models.Index(fields=['category'], name='product_bas_categor_46bd03_idx'),
        ),
        migrations.AddIndex(
            model_name='baseproduct',
            index=models.Index(fields=['subcategory'], name='product_bas_subcate_e09db9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baseproduct',
            unique_together={('name', 'category')},
        ),
    ]
