# Generated by Django 5.1.6 on 2025-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Fichier PDF du livre (si disponible).', null=True, upload_to='books/pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
